-- +migrate Up
CREATE TABLE groups (
	group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_name VARCHAR(100) not null,
	description varchar(255),
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	is_active bool not null default true
);
CREATE UNIQUE INDEX index_group_id ON groups(group_id);
-- +migrate Down
DROP TABLE groups;