-- +migrate Up
create table group_users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_id bigint not null,
	user_id bigint not null,
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	is_active bool not null default true,
	unique (user_id, group_id),
	constraint fk_group_id foreign key(group_id) references groups(group_id),
	constraint fk_user_id foreign key(user_id) references users(user_id)
);
CREATE UNIQUE INDEX index_group_group_id ON group_users(group_id);
CREATE UNIQUE INDEX index_group_user_id ON group_users(user_id);
-- +migrate Down
DROP TABLE group_users;