-- +migrate Up
CREATE TABLE bills (
	bill_description varchar(255),
	bill_title varchar(100),
	bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_id bigint not null,
	amount int not null default 0,
	is_active bool not null default true,
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	constraint fk_group_id foreign key(group_id) references groups(group_id)
);
CREATE UNIQUE INDEX index_bill_id ON bills(bill_id);
CREATE UNIQUE INDEX index_bills_group_id ON bills(group_id);
-- +migrate Down
DROP TABLE bills;