-- +migrate Up
create table user_bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	lend_user_id bigint not null,
	borrow_user_id bigint not null,
	bill_id bigint not null,
	group_id bigint not null,
	amount int not null default 0,
	is_active bool not null default true,
    created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
    check (lend_user_id <> borrow_user_id),
	constraint fk_group_id foreign key(group_id) references groups(group_id),
	constraint fk_lend_user_id foreign key(lend_user_id) references users(user_id),
	constraint fk_borrow_user_id foreign key(borrow_user_id) references users(user_id),
	constraint fk_bill_id foreign key(bill_id) references bills(bill_id)
);
CREATE UNIQUE INDEX index_user_bills_id ON user_bills(bill_id);
CREATE UNIQUE INDEX index_user_bills_group_id ON user_bills(group_id);
CREATE UNIQUE INDEX index_user_bills_lend_user_id ON user_bills(lend_user_id);
CREATE UNIQUE INDEX index_user_bills_borrow_user_id ON user_bills(borrow_user_id);
-- +migrate Down
DROP TABLE user_bills;