// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: groups.sql

package store

import (
	"context"
	"database/sql"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_name, description)
VALUES ($1, $2)
RETURNING group_id, group_name, description
`

type CreateGroupParams struct {
	GroupName   string         `json:"group_name"`
	Description sql.NullString `json:"description"`
}

type CreateGroupRow struct {
	GroupID     int64          `json:"group_id"`
	GroupName   string         `json:"group_name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.GroupName, arg.Description)
	var i CreateGroupRow
	err := row.Scan(&i.GroupID, &i.GroupName, &i.Description)
	return i, err
}

const deleteGroupById = `-- name: DeleteGroupById :exec
UPDATE groups
SET is_active = False
WHERE group_id = $1
`

func (q *Queries) DeleteGroupById(ctx context.Context, groupID int64) error {
	_, err := q.db.Exec(ctx, deleteGroupById, groupID)
	return err
}

const getGroupByGroupId = `-- name: GetGroupByGroupId :one
SELECT group_id, group_name, description
FROM groups
WHERE group_id = $1
AND is_active = True
`

type GetGroupByGroupIdRow struct {
	GroupID     int64          `json:"group_id"`
	GroupName   string         `json:"group_name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) GetGroupByGroupId(ctx context.Context, groupID int64) (GetGroupByGroupIdRow, error) {
	row := q.db.QueryRow(ctx, getGroupByGroupId, groupID)
	var i GetGroupByGroupIdRow
	err := row.Scan(&i.GroupID, &i.GroupName, &i.Description)
	return i, err
}

const hardDeleteUserById = `-- name: HardDeleteUserById :exec
DELETE FROM groups 
WHERE group_id = $1
`

func (q *Queries) HardDeleteUserById(ctx context.Context, groupID int64) error {
	_, err := q.db.Exec(ctx, hardDeleteUserById, groupID)
	return err
}
