// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, phone_number)
VALUES ($1, $2)
RETURNING user_id, user_name, phone_number, is_active, created_at, updated_at
`

type CreateUserParams struct {
	UserName    string         `json:"user_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserName, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_active = False
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, user_name, phone_number, is_active, created_at, updated_at
FROM users
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, userID)
	return err
}
